CORE_DIR  := ../core
SCRIPTS   := analysis/python
RESULTS   := results
FIGURES   := figures
LATEX     := latex

.PHONY: all data estimate sensitivity figures paper clean

all: data estimate sensitivity figures

# --- Data pipeline ---
data:
	python3 $(SCRIPTS)/01_download_data.py
	python3 $(SCRIPTS)/02_clean_merge.py
	python3 $(SCRIPTS)/03_sector_mapping.py
	python3 $(SCRIPTS)/04_descriptive_stats.py

# --- Estimation ---
estimate:
	python3 $(SCRIPTS)/05_gmm_estimation.py
	python3 $(SCRIPTS)/06_bayesian_estimation.py
	python3 $(SCRIPTS)/07_comparison.py

# --- ABM sensitivity ---
sensitivity:
	bash simulations/scripts/run_sensitivity.sh
	python3 $(SCRIPTS)/08_abm_sensitivity.py

# --- Figures (generated by individual scripts above) ---
figures:
	python3 $(SCRIPTS)/04_descriptive_stats.py
	python3 $(SCRIPTS)/05_gmm_estimation.py
	python3 $(SCRIPTS)/06_bayesian_estimation.py
	python3 $(SCRIPTS)/07_comparison.py
	python3 $(SCRIPTS)/08_abm_sensitivity.py

# --- Paper ---
paper:
	cd $(LATEX) && xelatex paper_en.tex && bibtex paper_en && xelatex paper_en.tex && xelatex paper_en.tex

clean:
	rm -f $(RESULTS)/*.csv $(FIGURES)/*.png
	rm -f $(LATEX)/*.aux $(LATEX)/*.bbl $(LATEX)/*.blg $(LATEX)/*.log $(LATEX)/*.out $(LATEX)/*.toc
